# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ac0c2a791abca4ae64a6a79c87ae5f4ffbe1be607d5b51a90cd04bb1f73fa9de15647608f5e2b4107927e3574ca5d4b4de7589547a7a1ec3a54f2bf626aa64

test:
  secret_key_base: 9356a55a1da0c51d57cc80f3c935baae735a23f43e4c6e725a56ab1d97cbd0dc9f2d434de33fc494b01874a70dfcdeb98caa3b60496998662c183946e65aca16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
